version: "3.8"

services:
  # Backend API
  api:
    build: ./fastapi-server
    container_name: rag-chatter-api
    ports:
      - "8888:8888"
    env_file:
      - ./fastapi-server/.env
    depends_on:
      - vector-db
    environment:
      - QDRANT_URL=http://vector-db:6333
    networks:
      - rag-network
    restart: unless-stopped

  # Frontend
  client:
    build: ./client
    container_name: rag-chatter-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8888
    depends_on:
      - api
    networks:
      - rag-network
    restart: unless-stopped

  # Vector Database
  vector-db:
    image: qdrant/qdrant:latest
    container_name: rag-chatter-vectordb
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  qdrant_data:

networks:
  rag-network:
    driver: bridge 